### ISSUE TITLE
reading and formatting a CSV or TXT file

### ISSUE THREAD

**Issue by chilliconkearney** [Shropshire-EGIT/Connor-s_text_adventure#1]
can anyone give me some pointers on how to format a CSV file, because I don't know how to layout my 'rooms' file, or how to access a dictionary in a text file.
[rooms.txt](https://github.com/Shropshire-EGIT/Connor-s_text_adventure/files/4022290/rooms.txt)

**Comment by JulieRose44** [comment]
Create it in Excel and do Save As .csv
-------- Original message --------From: chilliconkearney <notifications@github.com> Date: 04/01/2020  18:52  (GMT+00:00) To: Shropshire-EGIT/Connor-s_text_adventure <Connor-s_text_adventure@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Shropshire-EGIT/Connor-s_text_adventure] reading and formatting a
  CSV or TXT file (#1) can anyone give me some pointers on how to format a CSV file, because I don't know how to layout my 'rooms' file, or how to access a dictionary in a text
rooms.txt
file.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEGISE2HDFZA4US5HKLQ4DLGFA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IEA4WBA",
"url": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEGISE2HDFZA4US5HKLQ4DLGFA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IEA4WBA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by daveyholloway** [comment]
I wouldn't even use Excel, use a simple text editor but not notepad because it doesn't encode end of line characters properly. Notepad++ is one we use at work all the time at work. Just separate each field with a comma, if the field is empty then you'll just have two commas next to each other...

... maybe start off by listing the fields you want and what their positions in the line are...

**Comment by JulieRose44** [comment]
Excel just makes it a little easier to make sure you have the right data in the right columns 
-------- Original message --------From: Dave <notifications@github.com> Date: 04/01/2020  22:22  (GMT+00:00) To: Shropshire-EGIT/Connor-s_text_adventure <Connor-s_text_adventure@noreply.github.com> Cc: JulieRose44 <julie@ppprojects.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [Shropshire-EGIT/Connor-s_text_adventure] reading and formatting
  a CSV or TXT file (#1) I wouldn't even use Excel, use a simple text editor but not notepad because it doesn't encode end of line characters properly. Notepad++ is one we use at work all the time at work. Just separate each field with a comma, if the field is empty then you'll just have two commas next to each other...
... maybe start off by listing the fields you want and what their positions in the line are...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEDQDSIJ7BCB4YLVGDTQ4ED2TA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDBRLQ#issuecomment-570824878",
"url": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEDQDSIJ7BCB4YLVGDTQ4ED2TA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDBRLQ#issuecomment-570824878",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by daveyholloway** [comment]
Fair comment, I'd just worry that it might try to do something clever and leave tab characters or convert quotes to the wrong ones. But if it didn't then yes, that would be easier. 

Also, don't annoy the Project Manager 😛

**Comment by chilliconkearney** [comment]
got excel to mostly work.

just getting this error now:

File "c:\Users\chill\Downloads\Python\adventure.py", line 15, in <module>
    rooms = dict('rooms.csv')
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by JulieRose44** [comment]
If excel is losing leading zeros try putting ' before the numbers
-------- Original message --------From: chilliconkearney <notifications@github.com> Date: 05/01/2020  20:58  (GMT+00:00) To: Shropshire-EGIT/Connor-s_text_adventure <Connor-s_text_adventure@noreply.github.com> Cc: JulieRose44 <julie@ppprojects.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [Shropshire-EGIT/Connor-s_text_adventure] reading and formatting
  a CSV or TXT file (#1) got excel to mostly work.
just getting this error now:
File "c:\Users\chill\Downloads\Python\adventure.py", line 15, in 
rooms = dict('rooms.csv')
ValueError: dictionary update sequence element #0 has length 1; 2 is required

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEARVLRU7UIRZYUF253Q4JCVVA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEID7LDI#issuecomment-570946957",
"url": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEARVLRU7UIRZYUF253Q4JCVVA5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEID7LDI#issuecomment-570946957",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chilliconkearney** [comment]
I've had a go, but either the .csv file is wrong or my coding is wrong.

I tried switching the command that opens 'rooms.csv' as a dictionary from:

rooms = open(dict('rooms.csv'))

To:

rooms = dict(open('rooms.csv'))

And this error comes up:

ValueError: dictionary update sequence element #0 has length 54; 2 is required

**Comment by JulieRose44** [comment]
Have you imported the csv library as you have the time one?
-------- Original message --------From: chilliconkearney <notifications@github.com> Date: 06/01/2020  15:57  (GMT+00:00) To: Shropshire-EGIT/Connor-s_text_adventure <Connor-s_text_adventure@noreply.github.com> Cc: JulieRose44 <julie@ppprojects.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [Shropshire-EGIT/Connor-s_text_adventure] reading and formatting
  a CSV or TXT file (#1) I've had a go, but either the .csv file is wrong or my coding is wrong.
I tried switching the command that opens 'rooms.csv' as a dictionary from:
rooms = open(dict('rooms.csv'))
To:
rooms = dict(open('rooms.csv'))
And this error comes up:
ValueError: dictionary update sequence element #0 has length 1; 2 is required

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEEAHUP7A2B7HQYKRKDQ4NIE5A5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIF3X4Q#issuecomment-571194354",
"url": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/1?email_source=notifications\u0026email_token=AOFZLEEAHUP7A2B7HQYKRKDQ4NIE5A5CNFSM4KCXMHO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIF3X4Q#issuecomment-571194354",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chilliconkearney** [comment]
yes, I have.

I can put my current stage of coding in the project branch.

**Comment by chilliconkearney** [comment]
Think I figured it out. 
I didn't have a key: value in my .CSV file.
Thanks for the help 👍
