### ISSUE TITLE
class trouble

### ISSUE THREAD

**Issue by chilliconkearney** [Shropshire-EGIT/Connor-s_text_adventure#2]
lines 287 and 290 in the definitions file won't pick up the variable damage passed through with the class Enemy. 
I want to be able to easily create enemies for my text adventure, but the definition which contains the fighting won't accept damage as a variable within the current_enemy. 
I was wondering if there was any way around this that could still allow me to keep this definition separate from the main code.

**Comment by JulieRose44** [comment]
Do you need to either put quotes round damage or set damage as a variable and give it a value? This could be by passing it as a parameter in the function if the value is set elsewhere.
-------- Original message --------From: chilliconkearney <notifications@github.com> Date: 14/03/2020  12:12  (GMT+00:00) To: Shropshire-EGIT/Connor-s_text_adventure <Connor-s_text_adventure@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Shropshire-EGIT/Connor-s_text_adventure] class trouble (#2) 
lines 287 and 290 in the definitions file won't pick up the variable damage passed through with the class Enemy.
I want to be able to easily create enemies for my text adventure, but the definition which contains the fighting won't accept damage as a variable within the current_enemy.
I was wondering if there was any way around this that could still allow me to keep this definition separate from the main code.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/2",
"url": "https://github.com/Shropshire-EGIT/Connor-s_text_adventure/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chilliconkearney** [comment]
cheers.

just needed to add quotes round damage.
